#!/usr/bin/env bash

# Exit when a command fails (might cause problems with some pipes)
set -e

if [ ! -d "../aqua-examples" ]; then
    # Sparse checkout the aqua example repository (we only care about the python selenium project)
    echo "aqua-examples repository does not exist. Run first setup."
    mkdir -p ../aqua-examples
    pushd ../aqua-examples

    git init
    git remote add -f origin https://github.com/andagon/aqua-examples.git
    git config core.sparseCheckout true
    echo "integration examples/python-selenium" >> .git/info/sparse-checkout

    popd
fi

pushd ../aqua-examples

# Fetch current head of master and hard reset onto it
git fetch --depth=1 origin master
git reset --hard origin/master

# Setup project
cd integration\ examples/python-selenium
poetry install

popd

exit 0