#!/usr/bin/env bash

# Exit when a command fails (might cause problems with some pipes)
set -e

# Sparse checkout the auqa example repository (we only care about the python selenium project)
mkdir aqua-example
pushd aqua-example
git init
git remote add -f origin https://github.com/andagon/aqua-examples.git
git config core.sparseCheckout true
echo "integration examples/python-selenium" >> .git/info/sparse-checkout

# Now pull the master branch. We also limit the history
git pull --depth=1 origin master

# Setup project
cd integration\ examples/python-selenium
poetry install

popd

exit 0