#!/usr/bin/env bash

# Exit when a command fails (might cause problems with some pipes)
set -e

PROJECT_FOLDER="aqua-examples/integration\ examples/python-selenium/"

# Change directory to the project, but remember current directory
pushd $PROJECT_FOLDER

# run testcase
./main.py

# exit the project directory
popd

# Copy logs into the pickup directory. Those will be uploaded to aqua by the agent
cp $PROJECT_FOLDER/geckodriver.log ./toAttach/